// <auto-generated />
namespace passion__project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class music_project : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(music_project));
        
        string IMigrationMetadata.Id
        {
            get { return "202102192157560_music_project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
